[package]
name = "biblearchive"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.5"
lzokay-native = "0.1.0"
rcsubstring = "0.2.0"
bible-data = {git = "https://github.com/chrisjhh/bible-data"}

[dev-dependencies]
hex = "0.4.3"
crc32fast = "1.5.0"
